# Workflow: Auto-fix missing widget state metadata in all Jupyter notebooks
# Place this file in your repo under: .github/workflows/fix-widgets.yml

name: Auto-fix Widget Metadata

# Dispara em todo push que inclua notebooks
on:
  push:
    paths:
      - '**/*.ipynb'

jobs:
  patch-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbformat
        run: pip install nbformat

      - name: Patch widget metadata
        run: |
          python - << 'EOF'
          import glob
          import nbformat

          # Procura todos os notebooks na raiz e subpastas
          for path in glob.glob('**/*.ipynb', recursive=True):
              nb = nbformat.read(path, as_version=nbformat.NO_CONVERT)
              patched = False
              for cell in nb.cells:
                  wm = cell.metadata.get('widgets')
                  if wm is not None and 'state' not in wm:
                      wm['state'] = {}
                      patched = True
              if patched:
                  nbformat.write(nb, path)
          EOF

      - name: Commit and push auto-fix
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: auto-fix missing widget state metadata" || echo "No changes to commit"
          git push
